create table cars (
        id BIGSERIAL PRIMARY KEY NOT NULL,
        brand VARCHAR(100) NOT NULL,
        number INT NOT NULL,
        power INT NOT NULL,
        owner_id INT NOT NULL
    );
insert into cars (brand, number, power, owner_id) values ('Donkervoort', 7, 185, 1);
insert into cars (brand, number, power, owner_id) values ('Isuzu', 30, 326, 2);
insert into cars (brand, number, power, owner_id) values ('Donkervoort', 39, 347, 3);
insert into cars (brand, number, power, owner_id) values ('Roewe', 47, 179, 4);
insert into cars (brand, number, power, owner_id) values ('Skoda', 55, 283, 5);
insert into cars (brand, number, power, owner_id) values ('Noble', 62, 232, 6);
insert into cars (brand, number, power, owner_id) values ('TATA', 70, 338, 7);
insert into cars (brand, number, power, owner_id) values ('Metrocab', 77, 358, 8);
insert into cars (brand, number, power, owner_id) values ('Liebao Motor', 85, 174, 9);
insert into cars (brand, number, power, owner_id) values ('LTI', 92, 446, 10);
insert into cars (brand, number, power, owner_id) values ('Opel', 99, 354, 11);
insert into cars (brand, number, power, owner_id) values ('Ravon', 107, 272, 12);
insert into cars (brand, number, power, owner_id) values ('GMC', 114, 298, 13);
insert into cars (brand, number, power, owner_id) values ('DeSoto', 121, 285, 14);
insert into cars (brand, number, power, owner_id) values ('Tianye', 128, 128, 15);
insert into cars (brand, number, power, owner_id) values ('Aurus', 136, 319, 16);
insert into cars (brand, number, power, owner_id) values ('Porsche', 143, 262, 17);
insert into cars (brand, number, power, owner_id) values ('Think', 150, 409, 18);
insert into cars (brand, number, power, owner_id) values ('MINI', 157, 226, 19);
insert into cars (brand, number, power, owner_id) values ('Dallara', 164, 317, 20);
insert into cars (brand, number, power, owner_id) values ('Sears', 171, 311, 21);
insert into cars (brand, number, power, owner_id) values ('Plymouth', 179, 179, 22);
insert into cars (brand, number, power, owner_id) values ('Carbodies', 186, 171, 23);
insert into cars (brand, number, power, owner_id) values ('Geo', 193, 154, 24);
insert into cars (brand, number, power, owner_id) values ('Vortex', 200, 257, 25);
insert into cars (brand, number, power, owner_id) values ('Sears', 207, 392, 26);
insert into cars (brand, number, power, owner_id) values ('W Motors', 214, 491, 27);
insert into cars (brand, number, power, owner_id) values ('Hindustan', 221, 330, 28);
insert into cars (brand, number, power, owner_id) values ('JAC', 228, 387, 29);
insert into cars (brand, number, power, owner_id) values ('Tesla', 236, 365, 30);
insert into cars (brand, number, power, owner_id) values ('Horch', 243, 374, 31);
insert into cars (brand, number, power, owner_id) values ('SsangYong', 250, 381, 32);
insert into cars (brand, number, power, owner_id) values ('Great Wall', 257, 463, 33);
insert into cars (brand, number, power, owner_id) values ('DeSoto', 264, 192, 34);
insert into cars (brand, number, power, owner_id) values ('Bitter', 271, 228, 35);
insert into cars (brand, number, power, owner_id) values ('Infiniti', 278, 326, 36);
insert into cars (brand, number, power, owner_id) values ('ShuangHuan', 285, 433, 37);
insert into cars (brand, number, power, owner_id) values ('Changan', 292, 140, 38);
insert into cars (brand, number, power, owner_id) values ('Cupra', 299, 176, 39);
insert into cars (brand, number, power, owner_id) values ('Ford', 306, 263, 40);
insert into cars (brand, number, power, owner_id) values ('Smart', 314, 241, 41);
insert into cars (brand, number, power, owner_id) values ('Lucid', 321, 424, 42);
insert into cars (brand, number, power, owner_id) values ('Cord', 328, 415, 43);
insert into cars (brand, number, power, owner_id) values ('Maruti', 335, 105, 44);
insert into cars (brand, number, power, owner_id) values ('Roewe', 342, 471, 45);
insert into cars (brand, number, power, owner_id) values ('Venturi', 349, 377, 46);
insert into cars (brand, number, power, owner_id) values ('Dodge', 356, 381, 47);
insert into cars (brand, number, power, owner_id) values ('SEAT', 363, 204, 48);
insert into cars (brand, number, power, owner_id) values ('Steyr', 370, 210, 49);
insert into cars (brand, number, power, owner_id) values ('Mitsubishi', 377, 286, 50);
insert into cars (brand, number, power, owner_id) values ('LiXiang', 384, 493, 51);
insert into cars (brand, number, power, owner_id) values ('Suzuki', 391, 333, 52);
insert into cars (brand, number, power, owner_id) values ('Nash', 398, 133, 53);
insert into cars (brand, number, power, owner_id) values ('Bufori', 405, 231, 54);
insert into cars (brand, number, power, owner_id) values ('Borgward', 412, 254, 55);
insert into cars (brand, number, power, owner_id) values ('TVR', 420, 426, 56);
insert into cars (brand, number, power, owner_id) values ('Cizeta', 427, 247, 57);
insert into cars (brand, number, power, owner_id) values ('FSO', 434, 387, 58);
insert into cars (brand, number, power, owner_id) values ('Pontiac', 441, 204, 59);
insert into cars (brand, number, power, owner_id) values ('Nio', 448, 128, 60);
insert into cars (brand, number, power, owner_id) values ('McLaren', 455, 399, 61);
insert into cars (brand, number, power, owner_id) values ('Bitter', 462, 472, 62);
insert into cars (brand, number, power, owner_id) values ('Lucid', 469, 456, 63);
insert into cars (brand, number, power, owner_id) values ('Alpine', 476, 431, 64);
insert into cars (brand, number, power, owner_id) values ('Chrysler', 483, 309, 65);
insert into cars (brand, number, power, owner_id) values ('Excalibur', 490, 369, 66);
insert into cars (brand, number, power, owner_id) values ('Messerschmitt', 497, 292, 67);
insert into cars (brand, number, power, owner_id) values ('MG', 504, 191, 68);
insert into cars (brand, number, power, owner_id) values ('Cadillac', 511, 138, 69);
insert into cars (brand, number, power, owner_id) values ('Mazda', 518, 330, 70);
insert into cars (brand, number, power, owner_id) values ('Think', 525, 300, 71);
insert into cars (brand, number, power, owner_id) values ('Cupra', 532, 117, 72);
insert into cars (brand, number, power, owner_id) values ('Goggomobil', 539, 221, 73);
insert into cars (brand, number, power, owner_id) values ('Logem', 546, 468, 74);
insert into cars (brand, number, power, owner_id) values ('Mega', 553, 297, 75);
insert into cars (brand, number, power, owner_id) values ('Alpine', 560, 389, 76);
insert into cars (brand, number, power, owner_id) values ('Lotus', 567, 407, 77);
insert into cars (brand, number, power, owner_id) values ('Luxgen', 575, 397, 78);
insert into cars (brand, number, power, owner_id) values ('Pontiac', 582, 378, 79);
insert into cars (brand, number, power, owner_id) values ('Holden', 589, 300, 80);
insert into cars (brand, number, power, owner_id) values ('Haval', 596, 285, 81);
insert into cars (brand, number, power, owner_id) values ('DongFeng', 603, 119, 82);
insert into cars (brand, number, power, owner_id) values ('Saleen', 610, 110, 83);
insert into cars (brand, number, power, owner_id) values ('Ligier', 617, 161, 84);
insert into cars (brand, number, power, owner_id) values ('Eagle Cars', 624, 143, 85);
insert into cars (brand, number, power, owner_id) values ('Daihatsu', 631, 156, 86);
insert into cars (brand, number, power, owner_id) values ('Austin Healey', 638, 434, 87);
insert into cars (brand, number, power, owner_id) values ('Aurus', 645, 195, 88);
insert into cars (brand, number, power, owner_id) values ('Maserati', 652, 130, 89);
insert into cars (brand, number, power, owner_id) values ('Tianma', 659, 276, 90);
insert into cars (brand, number, power, owner_id) values ('Suzuki', 666, 145, 91);
insert into cars (brand, number, power, owner_id) values ('Steyr', 673, 326, 92);
insert into cars (brand, number, power, owner_id) values ('DeSoto', 680, 349, 93);
insert into cars (brand, number, power, owner_id) values ('Bugatti', 687, 287, 94);
insert into cars (brand, number, power, owner_id) values ('Suzuki', 694, 450, 95);
insert into cars (brand, number, power, owner_id) values ('Hindustan', 701, 494, 96);
insert into cars (brand, number, power, owner_id) values ('Delage', 708, 327, 97);
insert into cars (brand, number, power, owner_id) values ('Venturi', 715, 283, 98);
insert into cars (brand, number, power, owner_id) values ('Scion', 722, 488, 99);
insert into cars (brand, number, power, owner_id) values ('DeSoto', 729, 157, 100);