create table persons (
        id BIGSERIAL PRIMARY KEY NOT NULL,
        name VARCHAR(100) NOT NULL,
        birth_date DATE NOT NULL,
        country VARCHAR(100) NOT NULL,
        license_num INT NOT NULL
    );
insert into persons (name, birth_date, country, license_num) values ('Ronald Reeves', '1.11.1983', 'Bangladesh', 12);
insert into persons (name, birth_date, country, license_num) values ('Dennis Fields', '3.8.1979', 'Panama', 48);
insert into persons (name, birth_date, country, license_num) values ('Joseph Ballard', '23.4.1995', 'Guatemala', 86);
insert into persons (name, birth_date, country, license_num) values ('Steven Allen', '20.4.1963', 'Belgium', 126);
insert into persons (name, birth_date, country, license_num) values ('Matthew Larson', '23.4.1974', 'Guam', 168);
insert into persons (name, birth_date, country, license_num) values ('David Anderson', '7.7.1960', 'Zambia', 212);
insert into persons (name, birth_date, country, license_num) values ('William Hughes', '18.10.1997', 'Bangladesh', 258);
insert into persons (name, birth_date, country, license_num) values ('Richard Phillips', '26.3.1975', 'Germany', 306);
insert into persons (name, birth_date, country, license_num) values ('Antonio Snyder', '12.2.1965', 'Cyprus', 356);
insert into persons (name, birth_date, country, license_num) values ('Dustin Graham', '26.3.1951', 'Romania', 408);
insert into persons (name, birth_date, country, license_num) values ('Rick Norman', '8.9.1987', 'South Africa', 462);
insert into persons (name, birth_date, country, license_num) values ('John Lopez', '20.8.1959', 'Italy', 518);
insert into persons (name, birth_date, country, license_num) values ('Raymond Russell', '14.4.1970', 'U.S. Virgin Islands', 576);
insert into persons (name, birth_date, country, license_num) values ('James Mendez', '26.4.1993', 'Zambia', 636);
insert into persons (name, birth_date, country, license_num) values ('Keith Thomas', '8.9.1963', 'India', 698);
insert into persons (name, birth_date, country, license_num) values ('Barry Wallace', '5.9.1994', 'Montenegro', 762);
insert into persons (name, birth_date, country, license_num) values ('Michael Johnson', '9.11.2001', 'Guadeloupe', 828);
insert into persons (name, birth_date, country, license_num) values ('Sam Austin', '17.6.1986', 'Honduras', 896);
insert into persons (name, birth_date, country, license_num) values ('Craig Williams', '26.1.1975', 'Namibia', 966);
insert into persons (name, birth_date, country, license_num) values ('Mark Smith', '9.2.1982', 'Guatemala', 1038);
insert into persons (name, birth_date, country, license_num) values ('Matthew Hill', '12.7.1955', 'Zimbabwe', 1112);
insert into persons (name, birth_date, country, license_num) values ('James Mitchell', '3.3.1967', 'Iraq', 1188);
insert into persons (name, birth_date, country, license_num) values ('Jeremy Ward', '14.2.1964', 'Cayman Islands', 1266);
insert into persons (name, birth_date, country, license_num) values ('Edward Carter', '22.3.1961', 'Republic of Moldova', 1346);
insert into persons (name, birth_date, country, license_num) values ('Matthew Peters', '18.8.1970', 'Netherlands', 1428);
insert into persons (name, birth_date, country, license_num) values ('Patrick Powell', '17.1.1971', 'Hong Kong', 1512);
insert into persons (name, birth_date, country, license_num) values ('Glen Holt', '20.6.1968', 'Morocco', 1598);
insert into persons (name, birth_date, country, license_num) values ('Jeff Delgado', '10.9.1950', 'Taiwan', 1686);
insert into persons (name, birth_date, country, license_num) values ('John Johnson', '13.6.1950', 'Barbados', 1776);
insert into persons (name, birth_date, country, license_num) values ('James Ford', '10.11.1950', 'Australia', 1868);
insert into persons (name, birth_date, country, license_num) values ('Terrance Perkins', '21.1.1965', 'Portugal', 1962);
insert into persons (name, birth_date, country, license_num) values ('Edgar Smith', '12.9.1958', 'Andorra', 2058);
insert into persons (name, birth_date, country, license_num) values ('Jacob Owen', '19.10.1984', 'Namibia', 2156);
insert into persons (name, birth_date, country, license_num) values ('James Cummings', '13.8.1997', 'Angola', 2256);
insert into persons (name, birth_date, country, license_num) values ('Russell Elliott', '9.9.1960', 'Kenya', 2358);
insert into persons (name, birth_date, country, license_num) values ('David Taylor', '24.2.1983', 'Ireland', 2462);
insert into persons (name, birth_date, country, license_num) values ('Joseph Young', '24.7.1963', 'Norway', 2568);
insert into persons (name, birth_date, country, license_num) values ('Alex Ruiz', '22.5.1995', 'Iran', 2676);
insert into persons (name, birth_date, country, license_num) values ('Michael Hill', '26.2.1978', 'El Salvador', 2786);
insert into persons (name, birth_date, country, license_num) values ('Thomas Reyes', '7.5.1966', 'Serbia', 2898);
insert into persons (name, birth_date, country, license_num) values ('Joshua Fields', '26.10.1965', 'Iraq', 3012);
insert into persons (name, birth_date, country, license_num) values ('Chad Lopez', '15.3.1982', 'Hungary', 3128);
insert into persons (name, birth_date, country, license_num) values ('James Morgan', '2.8.1977', 'Azerbaijan', 3246);
insert into persons (name, birth_date, country, license_num) values ('Thomas Dawson', '14.10.1969', 'Namibia', 3366);
insert into persons (name, birth_date, country, license_num) values ('Paul Allen', '25.1.1959', 'Mauritius', 3488);
insert into persons (name, birth_date, country, license_num) values ('Ronald Taylor', '25.4.1987', 'Vietnam', 3612);
insert into persons (name, birth_date, country, license_num) values ('Willie Morales', '1.3.1959', 'Nepal', 3738);
insert into persons (name, birth_date, country, license_num) values ('Richard Carter', '11.7.1974', 'Guatemala', 3866);
insert into persons (name, birth_date, country, license_num) values ('Daniel Ramirez', '23.6.1964', 'Zimbabwe', 3996);
insert into persons (name, birth_date, country, license_num) values ('Daniel Brown', '19.10.1978', 'Germany', 4128);
insert into persons (name, birth_date, country, license_num) values ('Earl Williams', '23.10.1960', 'Tanzania', 4262);
insert into persons (name, birth_date, country, license_num) values ('Jimmy Colon', '5.8.1987', 'Myanmar [Burma]', 4398);
insert into persons (name, birth_date, country, license_num) values ('Tony Jones', '9.4.1994', 'Cayman Islands', 4536);
insert into persons (name, birth_date, country, license_num) values ('Glenn Holmes', '2.10.1987', 'Hashemite Kingdom of Jordan', 4676);
insert into persons (name, birth_date, country, license_num) values ('Christopher French', '4.6.1951', 'Morocco', 4818);
insert into persons (name, birth_date, country, license_num) values ('Theodore Gardner', '13.4.1967', 'Myanmar [Burma]', 4962);
insert into persons (name, birth_date, country, license_num) values ('Jonathan Howell', '22.6.1975', 'Armenia', 5108);
insert into persons (name, birth_date, country, license_num) values ('Raymond Walker', '2.11.1967', 'Mongolia', 5256);
insert into persons (name, birth_date, country, license_num) values ('Steve Hughes', '27.2.1963', 'South Africa', 5406);
insert into persons (name, birth_date, country, license_num) values ('Larry Hawkins', '12.3.1952', 'Zambia', 5558);
insert into persons (name, birth_date, country, license_num) values ('Joshua Larson', '24.1.1973', 'Barbados', 5712);
insert into persons (name, birth_date, country, license_num) values ('Allen Warren', '11.1.1984', 'Cayman Islands', 5868);
insert into persons (name, birth_date, country, license_num) values ('Joshua Smith', '2.8.1991', 'Suriname', 6026);
insert into persons (name, birth_date, country, license_num) values ('Kevin Barnett', '8.11.1993', 'Republic of Lithuania', 6186);
insert into persons (name, birth_date, country, license_num) values ('Fred Ward', '23.10.1997', 'Egypt', 6348);
insert into persons (name, birth_date, country, license_num) values ('Kirk Alvarado', '27.5.1973', 'Hong Kong', 6512);
insert into persons (name, birth_date, country, license_num) values ('Robert Clayton', '2.9.1971', 'Cyprus', 6678);
insert into persons (name, birth_date, country, license_num) values ('Walter Simmons', '11.10.1999', 'Uruguay', 6846);
insert into persons (name, birth_date, country, license_num) values ('Anthony Hamilton', '22.6.1962', 'Belize', 7016);
insert into persons (name, birth_date, country, license_num) values ('Christopher Morris', '13.8.1970', 'Palestine', 7188);
insert into persons (name, birth_date, country, license_num) values ('Andrew Ryan', '6.10.1956', 'Gabon', 7362);
insert into persons (name, birth_date, country, license_num) values ('David Neal', '7.4.1989', 'Latvia', 7538);
insert into persons (name, birth_date, country, license_num) values ('Adam Kennedy', '15.8.1989', 'Belize', 7716);
insert into persons (name, birth_date, country, license_num) values ('William Reid', '5.7.1995', 'Dominican Republic', 7896);
insert into persons (name, birth_date, country, license_num) values ('Karl Stone', '17.4.1953', 'Mauritius', 8078);
insert into persons (name, birth_date, country, license_num) values ('Lawrence Hoffman', '18.10.1964', 'Slovakia', 8262);
insert into persons (name, birth_date, country, license_num) values ('Robert Reed', '10.8.1952', 'Andorra', 8448);
insert into persons (name, birth_date, country, license_num) values ('Melvin Johnson', '13.11.1977', 'Jamaica', 8636);
insert into persons (name, birth_date, country, license_num) values ('Scott Williamson', '22.2.1980', 'San Marino', 8826);
insert into persons (name, birth_date, country, license_num) values ('Andrew Hamilton', '17.7.1961', 'Palestine', 9018);
insert into persons (name, birth_date, country, license_num) values ('William Dean', '22.2.1986', 'Guatemala', 9212);
insert into persons (name, birth_date, country, license_num) values ('Charlie Miller', '10.6.1959', 'Kuwait', 9408);
insert into persons (name, birth_date, country, license_num) values ('Clarence Moore', '12.10.1996', 'Bangladesh', 9606);
insert into persons (name, birth_date, country, license_num) values ('Carl Clark', '8.7.1957', 'Swaziland', 9806);
insert into persons (name, birth_date, country, license_num) values ('Jack Parks', '16.4.1961', 'Palestine', 10008);
insert into persons (name, birth_date, country, license_num) values ('Don Johnson', '14.1.1980', 'Guatemala', 10212);
insert into persons (name, birth_date, country, license_num) values ('Leonard Oliver', '16.8.1999', 'United States', 10418);
insert into persons (name, birth_date, country, license_num) values ('Frank Miller', '23.1.1989', 'United States', 10626);
insert into persons (name, birth_date, country, license_num) values ('Gabriel Anderson', '7.1.1952', 'France', 10836);
insert into persons (name, birth_date, country, license_num) values ('Corey Harris', '18.6.2000', 'Bosnia and Herzegovina', 11048);
insert into persons (name, birth_date, country, license_num) values ('Steve Evans', '4.5.1985', 'Liechtenstein', 11262);
insert into persons (name, birth_date, country, license_num) values ('Lee Jones', '6.6.1957', 'Honduras', 11478);
insert into persons (name, birth_date, country, license_num) values ('Norman Green', '25.7.1961', 'Republic of Korea', 11696);
insert into persons (name, birth_date, country, license_num) values ('Joseph Hunt', '22.2.1967', 'Bahamas', 11916);
insert into persons (name, birth_date, country, license_num) values ('Tony Evans', '22.5.1956', 'Czech Republic', 12138);
insert into persons (name, birth_date, country, license_num) values ('Thomas Padilla', '23.8.1990', 'South Africa', 12362);
insert into persons (name, birth_date, country, license_num) values ('Paul Johnson', '7.2.1983', 'Bahrain', 12588);
insert into persons (name, birth_date, country, license_num) values ('Willard Clark', '1.8.1978', 'Switzerland', 12816);
insert into persons (name, birth_date, country, license_num) values ('Henry Ellis', '20.10.1983', 'Aruba', 13046);
insert into persons (name, birth_date, country, license_num) values ('Miguel Johnson', '19.3.1993', 'Italy', 13278);